/** @format */

import "./globals.css"
import { Inter } from "next/font/google"
import Navbar from "@/app/components/Navbar"
import Footer from "@/app/components/Footer"
import { Providers } from "@/lib/provider"
import BackToTopBtn from "@/app/components/BackToTop"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Levan Dolidze",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`${inter.className} mx-auto flex	 min-h-screen  max-w-screen-2xl flex-col bg-gradient-body text-white`}
        >
          <Navbar />

          <BackToTopBtn />

          <main className="grow px-8">{children}</main>
          <Footer />
        </body>
      </html>
    </Providers>
  )
}
